### ISSUE TITLE
No files in S3 Bucket

### ISSUE THREAD

**Issue by cbg-teamomni** [0x4447/0x4447-cli-node-potato#42]
Potato created the cert, S3 bucket with the policy, and Route53 entries but did not upload any files to the bucket. No error messages were displayed. Another run was tried with the update function but still no files were uploaded.

**Comment by davidgatti** [comment]
Please provide two things:

- the command that you used
- to a `ls -la` to show the folder/file structure.

**Comment by cbg-teamomni** [comment]
As requested.

`potato -s ~/Arsenal/Projects/marketing-site

cgaeth@cgaeth-TeamOMNI ~ % ls -la ~/Arsenal/Projects/marketing-site
total 616
drwxr-xr-x@ 23 cgaeth  staff    736 Apr 17 09:46 .
drwxr-xr-x   8 cgaeth  staff    256 Apr 13 11:19 ..
-rw-r--r--   1 cgaeth  staff   6148 Apr 17 09:55 .DS_Store
drwxr-xr-x  12 cgaeth  staff    384 Apr 16 11:44 .git
-rw-r--r--   1 cgaeth  staff    327 Apr 16 15:54 .htaccess
-rw-rw-r--   1 cgaeth  staff  11977 Apr 15 17:49 401.html
-rw-rw-r--   1 cgaeth  staff  11237 Apr 15 17:48 404.html
-rw-rw-r--   1 cgaeth  staff  16836 Apr 15 17:58 about-us.html
-rw-rw-r--   1 cgaeth  staff  16960 Apr 15 18:01 contact-us.html
drwxrwxr-x   5 cgaeth  staff    160 Apr 15 17:49 css
-rw-rw-r--   1 cgaeth  staff  12565 Apr 15 17:49 detail_post.html
drwxrwxr-x   6 cgaeth  staff    192 Apr 15 17:49 fonts
drwxrwxr-x  74 cgaeth  staff   2368 Apr 16 11:43 images
-rw-rw-r--@  1 cgaeth  staff  22814 Apr 17 07:59 index.html
drwxrwxr-x   3 cgaeth  staff     96 Apr 15 17:49 js
-rw-rw-r--   1 cgaeth  staff  16941 Apr 15 18:20 login.html
-rw-rw-r--   1 cgaeth  staff  27152 Apr 15 18:28 privacy-policy.html
-rw-rw-r--   1 cgaeth  staff  16042 Apr 15 18:31 recover-password.html
-rw-rw-r--   1 cgaeth  staff  17885 Apr 15 18:48 register.html
-rw-rw-r--   1 cgaeth  staff  19074 Apr 15 18:49 request-a-demo.html
-rw-r--r--@  1 cgaeth  staff  18878 Apr 16 15:49 services.html
-rw-rw-r--@  1 cgaeth  staff  28768 Apr 15 19:09 solutions.html
-rw-rw-r--   1 cgaeth  staff  34856 Apr 15 19:10 terms-of-service.html

**Comment by davidgatti** [comment]
I see, you have here a mix of folder, hidden folder, hidden files etc. Try putting just the files that you want in s3 in a separated folder (you don't want .git in s3 for example), and point to this new folder. See if this fixes the problem.

**Comment by cbg-teamomni** [comment]
I just attempted this. No hidden files or folders. Still no upload.

**Comment by davidgatti** [comment]
Hmm this is odd. lets do this, pick a time that works for you using this link: https://calendly.com/0x4447/60min?month=2020-04&date=2020-04-23 for the 23th, and we can do a screen share to see what is going on.

**Comment by davidgatti** [comment]
One last try before we schedule a meeting, you are making a path using `~`, can you use the full path to the folder. And see if that helps?
